name: MLops Pipeline

on:
  push:
    branches: [main]

env:
    AWS_REGION: us-east-1
    S3_BUCKET_NAME: mlops-pipeline-bucket

jobs:
    train-and-deploy: 
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            
            - name: Generate dataset
              run: |
                python3 generate_data.py

            - name: Train model
              run: |
                python3 train.py

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: push model to S3
              run: |
                aws s3 cp models/churn_model.pkl s3://${{ env.S3_BUCKET_NAME }}/models/churn_model.pkl --region ${{ env.AWS_REGION }}
                echo "Model pushed to S3 successfully."

            - name: Update inference.yaml with new model path
              run: |
                sed -i 's|storageUri: .*|storageUri: s3://${{ env.S3_BUCKET_NAME }}/model/churn_model.pkl|' inference.yaml

            - name: commit updated inference.yaml
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add inference.yaml
                git commit -m "Update inference.yaml with new model path"
                git push origin main


